# This is the Data Sources page and all of its contents
creditsPage <- tabPanel("About",
                        tags$div(class="titlePanel",
                                 tags$h3(strong(class="title",
                                         "About"), 
                                         align = "center")
                        ),
                        HTML('<center><img src="NSS-logo.png" height="125 width="125"></center>'),
                        tags$hr(),
                        tags$div(class="bodyTextContainer",
                                 tags$h5(strong("Contributors"), style = "font-size:16px;"),
                                 tags$p("My name is Oluchi Nwosu Randolph. This web app is my midcourse", 
                                 "project as a member of Nashville Software School's Data Science 4 Cohort.",
                                 "Feel free to check out my Git repo",
                                 a(href='https://github.com/ocnrandolph/midcourse-shiny', 'https://github.com/ocnrandolph/midcourse-shiny'),
                                 "if you'd like more information about this project and my code.", style = "font-size:16px;"),
                                 br(),
                                 p("I'd like to thank my instructors, Michael Holloway, Tim Dobbins, Tingting Duan,",
                                 "and Suneethi Sivakumaran Ford, for their advice and patience while teaching us how to",
                                 "navigate r shiny. I'd also like to thank my cohort for the laughs, encouragement, and great questions",
                                 "that kept learning fun along the way. Special thanks to Veronica Ikeshoji-Orlati and",
                                 "Maeva Ralafiarindaza for always being willing to help others, give feedback, and share what you know.",
                                 "Last, but not least, a big thank you my friends and family who have supported me in countless ways, especially",
                                 "Jake Randolph, for everything that you all have done to support me in this and every endeavor.", style = "font-size:16px;"),
                                 hr(),
                                 tags$h5(strong("Data Sources"), style = "font-size:16px;"),
                                 tags$p(a(href='https://www.wrapsnet.org/admissions-and-arrivals/', 'Historical U.S. Refugee Admissions Data')),
                                 tags$p(a(href='https://www.migrationpolicy.org/programs/data-hub/charts/us-annual-refugee-resettlement-ceilings-and-number-refugees-admitted-united', 'Refugee Admission Ceiling and Arrival Data')),
                                 tags$p(a(href='https://www.census.gov/programs-surveys/acs', '2008 ACS 3-year estimates'), 'via the R package', a(href='https://walker-data.com/tidycensus/', 'tidycensus')),
                                 tags$p(a(href='https://www.census.gov/programs-surveys/acs', '2018 ACS 5-year estimates'), 'via tidycensus'),
                                 tags$p(a(href='https://crime-data-explorer.fr.cloud.gov/', 'FBI Crime Data Explorer')),
                                 hr(),
                                 tags$h5(strong("Additional Resources"), style = "font-size:16px;"),
                                 tags$p(a(href='https://immigrationlab.org/project/harnessing-big-data-to-improve-refugee-resettlement/', "Machine Learning to Improve Refugee Resettlement"), '- a research article'),
                                 tags$p(a(href='https://data.newamericaneconomy.org/en/refugee-resettlement-us/', 'New American Economy Data Interactive - Refugee Resettlement in U.S. Cities'), '- more data exploration'),
                                 tags$p(a(href='http://www.tnrefugees.org/index.php/faqs/#what-is-the-difference-between-a-refugee-and-an-asylee', 'FAQs - TN Office for Refugees'), '- answers to a range of questions'),
                                 tags$p(a(href='https://immigrationforum.org/article/fact-sheet-u-s-refugee-resettlement/', 'U.S. Refugee Resettlement Fact Sheet - National Immigration Forum'), '- details on the resettlement process'),
                                 br()
                        )
)