takeawayPage <- tabPanel('The Takeaway',
                         h3("Concluding Thoughts", align = "center"),
                         br(),
                         p("Refugee arrivals have limited say in their resettlement destinations, and once resettled in the U.S. they are free",
                           "to move to wherever they choose. So it is no surprise that they move to other locations.", 
                           align = "center", style = "font-size:16px;"),
                         br(),
                         p("When comparing major initial resettlement locations to secondary migration locations on a handful of characteristics",
                           "(racial composition, unemployment rate, immigrant and African population, and crime rate), we see that there are some",
                           "interesting differences that spur additional questions:", align = "left", style = "font-size:16px;"),
                         br(),
                         p("* Atlanta, GA (DeKalb County), an initial resettlement location, has a higher proportion of people who racially identify",
                           "as Black than any of the secondary migration locations listed. Qualitative and quantitative research findings and",
                           "analyses from other sources show an outflow of Somali refugees from Atlanta, GA to cities with higher proportions of people",
                           "who racially identify as White (e.g., Minneapolis in Hennepin County, MN and Lewiston in Androscoggin County, ME).",
                           strong("Does race meaningfully impact the ways in which resettled Somali refugees socially and economically integrate in a community?"),
                           "If so, how?", align = "left", style = "font-size:16px;"),
                         br(),
                         p("*", strong(a(href='http://africamigration.com/issue/dec2011/Kimberly-Huisman_Why-Maine.pdf', "Qualitative studies")), 
                           "have shown that some Somali refugees have moved to Lewiston, ME (Androscoggin County)",
                           strong(a(href='https://www.usf.edu/arts-sciences/institutes/black-life/document/akiwumi-ibl-conference-feb-5-2019b.pdf', "from Clarkston, GA (DeKalb County)")),
                           "because it is safer. When comparing incidences of crime in Maine and Georgia, this appears to be the case in every area except",
                           "reports of rape. Whether looking at 2009 or 2019 data, Maine reports higher occurrences of this specific indicator of crime and safety.", 
                           strong("Are the differences we observe here statistically significant?"), "And might perceptions of safety differ based on an",
                           "individual's gender or family composition? Would additional county or city-level crime data paint a different picture?", 
                           align = "left", style = "font-size:16px;"),
                         br(),
                         p("* Population migration data show resettled Somali refugees moving from larger cities like Dallas, TX (Dallas County)", 
                           "and Seattle, WA (King County) to St. Cloud, MN (Stearns County). Given that Minneapolis is categorized as",
                           strong(a(href='https://www.brookings.edu/wp-content/uploads/2016/07/Gateways-2014-update-1.pdf', "a more established gateway city")), 
                           "for immigrants and refugees, what could be driving Somalis to St. Cloud? Compared to Dallas and Seattle,",
                           "St. Cloud was less racially diverse, had higher unemployment rates for people racialized as Black, but",
                           "a higher proportion of foreign born Africans within it's immigrant population in 2019.",
                           strong("What other community and state-level factors could play a role in this observed trend?"), 
                           align = "left", style = "font-size:16px;"),
                         br(),
                         p(strong(a(href='https://immigrationlab.org/project/harnessing-big-data-to-improve-refugee-resettlement/', "Valuable research")), 
                           "is being done on algorithms that can be used to resettle refugees in locations that are more likely to lead to", 
                           "faster economic integration. What other community characteristics matter as resettled refugees pursue integration and belonging in",
                           "a new country? The preliminary analyses explored in this app address and spark questions that move us toward a larger line of inquiry:", 
                           em("are the differences in locations meaningfully different in ways that influence resettled refugees' decisions to move in pursuit of economic opportunity, social integration, and belonging?"),
                           "The types of questions prompted by the quick comparisons here should be addressed in order to holistically improve the effectiveness of refugee",
                           "resettlement processes for individuals and communities alike.", align = "center", style = "font-size:16px;"),
                         h3("Future Directions", align = "center"),
                         br(),
                         p("Additional research in this area can be both more in-depth (focusing on Somali refugees in particular and the different ethnic groups within this community), and more",
                           "broad (exploring how navigating resettlement differs for refugees from other countries of origin).",
                           "Moreover, energy should also be dedicated to people within resettlement communities, the other side of the resettlement",
                           "relationship. For cities and towns concerned about newcomers leaving, what (if anything) can be done to better help them", 
                           "retain refugee and immigrant populations? For places that are unhappy about the influxes of newcomers that they are", 
                           "receiving, what (if anything) can be done to address their concerns? Overall, the integration process is a group effort.",
                           "My hope is that our research, policies, and efforts operate with this reality in mind.", align = "center", 
                           style = "font-size:16px;")
)